//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Dec 10 02:17:50 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// RDY_put_A                      O     1
// RDY_put_B                      O     1
// get_res                        O    64 reg
// RDY_get_res                    O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_A_a_in                     I    64 reg
// put_B_b_in                     I    64 reg
// EN_put_A                       I     1
// EN_put_B                       I     1
// EN_get_res                     I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFPMul64(CLK,
		 RST_N,

		 put_A_a_in,
		 EN_put_A,
		 RDY_put_A,

		 put_B_b_in,
		 EN_put_B,
		 RDY_put_B,

		 EN_get_res,
		 get_res,
		 RDY_get_res);
  input  CLK;
  input  RST_N;

  // action method put_A
  input  [63 : 0] put_A_a_in;
  input  EN_put_A;
  output RDY_put_A;

  // action method put_B
  input  [63 : 0] put_B_b_in;
  input  EN_put_B;
  output RDY_put_B;

  // actionvalue method get_res
  input  EN_get_res;
  output [63 : 0] get_res;
  output RDY_get_res;

  // signals for module outputs
  wire [63 : 0] get_res;
  wire RDY_get_res, RDY_put_A, RDY_put_B;

  // register answer
  reg [63 : 0] answer;
  wire [63 : 0] answer$D_IN;
  wire answer$EN;

  // register exponent_res_normalised_1
  reg [11 : 0] exponent_res_normalised_1;
  wire [11 : 0] exponent_res_normalised_1$D_IN;
  wire exponent_res_normalised_1$EN;

  // register exponent_res_normalised_2
  reg [10 : 0] exponent_res_normalised_2;
  wire [10 : 0] exponent_res_normalised_2$D_IN;
  wire exponent_res_normalised_2$EN;

  // register exponent_res_normalised_3
  reg [10 : 0] exponent_res_normalised_3;
  wire [10 : 0] exponent_res_normalised_3$D_IN;
  wire exponent_res_normalised_3$EN;

  // register exponent_res_overbiased_1
  reg [11 : 0] exponent_res_overbiased_1;
  wire [11 : 0] exponent_res_overbiased_1$D_IN;
  wire exponent_res_overbiased_1$EN;

  // register exponent_res_overbiased_2
  reg [11 : 0] exponent_res_overbiased_2;
  wire [11 : 0] exponent_res_overbiased_2$D_IN;
  wire exponent_res_overbiased_2$EN;

  // register got_A
  reg got_A;
  wire got_A$D_IN, got_A$EN;

  // register got_B
  reg got_B;
  wire got_B$D_IN, got_B$EN;

  // register got_final
  reg got_final;
  wire got_final$D_IN, got_final$EN;

  // register input_1_64
  reg [63 : 0] input_1_64;
  wire [63 : 0] input_1_64$D_IN;
  wire input_1_64$EN;

  // register input_2_64
  reg [63 : 0] input_2_64;
  wire [63 : 0] input_2_64$D_IN;
  wire input_2_64$EN;

  // register mantissa_A
  reg [51 : 0] mantissa_A;
  wire [51 : 0] mantissa_A$D_IN;
  wire mantissa_A$EN;

  // register mantissa_B
  reg [51 : 0] mantissa_B;
  wire [51 : 0] mantissa_B$D_IN;
  wire mantissa_B$EN;

  // register mantissa_res_non_normalised
  reg [105 : 0] mantissa_res_non_normalised;
  wire [105 : 0] mantissa_res_non_normalised$D_IN;
  wire mantissa_res_non_normalised$EN;

  // register mantissa_res_non_normalised_reduced
  reg [51 : 0] mantissa_res_non_normalised_reduced;
  wire [51 : 0] mantissa_res_non_normalised_reduced$D_IN;
  wire mantissa_res_non_normalised_reduced$EN;

  // register mantissa_res_normalised
  reg [51 : 0] mantissa_res_normalised;
  wire [51 : 0] mantissa_res_normalised$D_IN;
  wire mantissa_res_normalised$EN;

  // register sign_out
  reg sign_out;
  wire sign_out$D_IN, sign_out$EN;

  // register stage1
  reg stage1;
  wire stage1$D_IN, stage1$EN;

  // register stage2
  reg stage2;
  wire stage2$D_IN, stage2$EN;

  // register stage3
  reg stage3;
  wire stage3$D_IN, stage3$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_exponentNormalisation,
       CAN_FIRE_RL_finalResult,
       CAN_FIRE_RL_mantissaNormalisation,
       CAN_FIRE_RL_preprocessing,
       CAN_FIRE_get_res,
       CAN_FIRE_put_A,
       CAN_FIRE_put_B,
       WILL_FIRE_RL_exponentNormalisation,
       WILL_FIRE_RL_finalResult,
       WILL_FIRE_RL_mantissaNormalisation,
       WILL_FIRE_RL_preprocessing,
       WILL_FIRE_get_res,
       WILL_FIRE_put_A,
       WILL_FIRE_put_B;

  // remaining internal signals
  wire [211 : 0] _1_CONCAT_mantissa_A_9_0_MUL_1_CONCAT_mantissa__ETC___d23;
  wire [105 : 0] mantissa_res_non_normalised_SL_IF_mantissa_res_ETC__q1;
  wire [63 : 0] x__h6362;
  wire [31 : 0] IF_mantissa_res_non_normalised_6_BIT_101_28_AN_ETC___d450,
		IF_mantissa_res_non_normalised_6_BIT_11_8_AND__ETC___d540,
		IF_mantissa_res_non_normalised_6_BIT_14_4_AND__ETC___d537,
		IF_mantissa_res_non_normalised_6_BIT_17_0_AND__ETC___d534,
		IF_mantissa_res_non_normalised_6_BIT_20_6_AND__ETC___d531,
		IF_mantissa_res_non_normalised_6_BIT_23_2_AND__ETC___d528,
		IF_mantissa_res_non_normalised_6_BIT_26_8_AND__ETC___d525,
		IF_mantissa_res_non_normalised_6_BIT_29_4_AND__ETC___d522,
		IF_mantissa_res_non_normalised_6_BIT_2_0_AND_N_ETC___d549,
		IF_mantissa_res_non_normalised_6_BIT_32_0_AND__ETC___d519,
		IF_mantissa_res_non_normalised_6_BIT_35_6_AND__ETC___d516,
		IF_mantissa_res_non_normalised_6_BIT_38_02_AND_ETC___d513,
		IF_mantissa_res_non_normalised_6_BIT_41_08_AND_ETC___d510,
		IF_mantissa_res_non_normalised_6_BIT_44_14_AND_ETC___d507,
		IF_mantissa_res_non_normalised_6_BIT_47_20_AND_ETC___d504,
		IF_mantissa_res_non_normalised_6_BIT_50_26_AND_ETC___d501,
		IF_mantissa_res_non_normalised_6_BIT_53_32_AND_ETC___d498,
		IF_mantissa_res_non_normalised_6_BIT_56_38_AND_ETC___d495,
		IF_mantissa_res_non_normalised_6_BIT_59_44_AND_ETC___d492,
		IF_mantissa_res_non_normalised_6_BIT_5_6_AND_N_ETC___d546,
		IF_mantissa_res_non_normalised_6_BIT_62_50_AND_ETC___d489,
		IF_mantissa_res_non_normalised_6_BIT_65_56_AND_ETC___d486,
		IF_mantissa_res_non_normalised_6_BIT_68_62_AND_ETC___d483,
		IF_mantissa_res_non_normalised_6_BIT_71_68_AND_ETC___d480,
		IF_mantissa_res_non_normalised_6_BIT_74_74_AND_ETC___d477,
		IF_mantissa_res_non_normalised_6_BIT_77_80_AND_ETC___d474,
		IF_mantissa_res_non_normalised_6_BIT_80_86_AND_ETC___d471,
		IF_mantissa_res_non_normalised_6_BIT_83_92_AND_ETC___d468,
		IF_mantissa_res_non_normalised_6_BIT_86_98_AND_ETC___d465,
		IF_mantissa_res_non_normalised_6_BIT_89_04_AND_ETC___d462,
		IF_mantissa_res_non_normalised_6_BIT_8_2_AND_N_ETC___d543,
		IF_mantissa_res_non_normalised_6_BIT_92_10_AND_ETC___d459,
		IF_mantissa_res_non_normalised_6_BIT_95_16_AND_ETC___d456,
		IF_mantissa_res_non_normalised_6_BIT_98_22_AND_ETC___d453;
  wire [11 : 0] x__h829, y__h830;
  wire [10 : 0] IF_mantissa_res_non_normalised_6_BIT_101_28_AN_ETC___d559,
		IF_mantissa_res_non_normalised_6_BIT_11_8_AND__ETC___d649,
		IF_mantissa_res_non_normalised_6_BIT_14_4_AND__ETC___d646,
		IF_mantissa_res_non_normalised_6_BIT_17_0_AND__ETC___d643,
		IF_mantissa_res_non_normalised_6_BIT_20_6_AND__ETC___d640,
		IF_mantissa_res_non_normalised_6_BIT_23_2_AND__ETC___d637,
		IF_mantissa_res_non_normalised_6_BIT_26_8_AND__ETC___d634,
		IF_mantissa_res_non_normalised_6_BIT_29_4_AND__ETC___d631,
		IF_mantissa_res_non_normalised_6_BIT_2_0_AND_N_ETC___d658,
		IF_mantissa_res_non_normalised_6_BIT_32_0_AND__ETC___d628,
		IF_mantissa_res_non_normalised_6_BIT_35_6_AND__ETC___d625,
		IF_mantissa_res_non_normalised_6_BIT_38_02_AND_ETC___d622,
		IF_mantissa_res_non_normalised_6_BIT_41_08_AND_ETC___d619,
		IF_mantissa_res_non_normalised_6_BIT_44_14_AND_ETC___d616,
		IF_mantissa_res_non_normalised_6_BIT_47_20_AND_ETC___d613,
		IF_mantissa_res_non_normalised_6_BIT_50_26_AND_ETC___d610,
		IF_mantissa_res_non_normalised_6_BIT_53_32_AND_ETC___d607,
		IF_mantissa_res_non_normalised_6_BIT_56_38_AND_ETC___d604,
		IF_mantissa_res_non_normalised_6_BIT_59_44_AND_ETC___d601,
		IF_mantissa_res_non_normalised_6_BIT_5_6_AND_N_ETC___d655,
		IF_mantissa_res_non_normalised_6_BIT_62_50_AND_ETC___d598,
		IF_mantissa_res_non_normalised_6_BIT_65_56_AND_ETC___d595,
		IF_mantissa_res_non_normalised_6_BIT_68_62_AND_ETC___d592,
		IF_mantissa_res_non_normalised_6_BIT_71_68_AND_ETC___d589,
		IF_mantissa_res_non_normalised_6_BIT_74_74_AND_ETC___d586,
		IF_mantissa_res_non_normalised_6_BIT_77_80_AND_ETC___d583,
		IF_mantissa_res_non_normalised_6_BIT_80_86_AND_ETC___d580,
		IF_mantissa_res_non_normalised_6_BIT_83_92_AND_ETC___d577,
		IF_mantissa_res_non_normalised_6_BIT_86_98_AND_ETC___d574,
		IF_mantissa_res_non_normalised_6_BIT_89_04_AND_ETC___d571,
		IF_mantissa_res_non_normalised_6_BIT_8_2_AND_N_ETC___d652,
		IF_mantissa_res_non_normalised_6_BIT_92_10_AND_ETC___d568,
		IF_mantissa_res_non_normalised_6_BIT_95_16_AND_ETC___d565,
		IF_mantissa_res_non_normalised_6_BIT_98_22_AND_ETC___d562,
		shif__h6137;
  wire NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240,
       NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330,
       NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327,
       NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324,
       NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321,
       NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318,
       NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315,
       NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312,
       NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309,
       NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306,
       NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303,
       NOT_mantissa_res_non_normalised_6_BIT_3_2_3_AN_ETC___d339,
       NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300,
       NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297,
       NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294,
       NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291,
       NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288,
       NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285,
       NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282,
       NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279,
       NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276,
       NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273,
       NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336,
       NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270,
       NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267,
       NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264,
       NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261,
       NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258,
       NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255,
       NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252,
       NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249,
       NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246,
       NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243,
       NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333,
       mantissa_res_non_normalised_6_BIT_0_7_AND_NOT__ETC___d342,
       mantissa_res_non_normalised_6_BIT_102_30_AND_N_ETC___d444,
       mantissa_res_non_normalised_6_BIT_12_0_AND_NOT_ETC___d354,
       mantissa_res_non_normalised_6_BIT_15_6_AND_NOT_ETC___d357,
       mantissa_res_non_normalised_6_BIT_18_2_AND_NOT_ETC___d360,
       mantissa_res_non_normalised_6_BIT_21_8_AND_NOT_ETC___d363,
       mantissa_res_non_normalised_6_BIT_24_4_AND_NOT_ETC___d366,
       mantissa_res_non_normalised_6_BIT_27_0_AND_NOT_ETC___d369,
       mantissa_res_non_normalised_6_BIT_30_6_AND_NOT_ETC___d372,
       mantissa_res_non_normalised_6_BIT_33_2_AND_NOT_ETC___d375,
       mantissa_res_non_normalised_6_BIT_36_8_AND_NOT_ETC___d378,
       mantissa_res_non_normalised_6_BIT_39_04_AND_NO_ETC___d381,
       mantissa_res_non_normalised_6_BIT_3_2_AND_NOT__ETC___d345,
       mantissa_res_non_normalised_6_BIT_42_10_AND_NO_ETC___d384,
       mantissa_res_non_normalised_6_BIT_45_16_AND_NO_ETC___d387,
       mantissa_res_non_normalised_6_BIT_48_22_AND_NO_ETC___d390,
       mantissa_res_non_normalised_6_BIT_51_28_AND_NO_ETC___d393,
       mantissa_res_non_normalised_6_BIT_54_34_AND_NO_ETC___d396,
       mantissa_res_non_normalised_6_BIT_57_40_AND_NO_ETC___d399,
       mantissa_res_non_normalised_6_BIT_60_46_AND_NO_ETC___d402,
       mantissa_res_non_normalised_6_BIT_63_52_AND_NO_ETC___d405,
       mantissa_res_non_normalised_6_BIT_66_58_AND_NO_ETC___d408,
       mantissa_res_non_normalised_6_BIT_69_64_AND_NO_ETC___d411,
       mantissa_res_non_normalised_6_BIT_6_8_AND_NOT__ETC___d348,
       mantissa_res_non_normalised_6_BIT_72_70_AND_NO_ETC___d414,
       mantissa_res_non_normalised_6_BIT_75_76_AND_NO_ETC___d417,
       mantissa_res_non_normalised_6_BIT_78_82_AND_NO_ETC___d420,
       mantissa_res_non_normalised_6_BIT_81_88_AND_NO_ETC___d423,
       mantissa_res_non_normalised_6_BIT_84_94_AND_NO_ETC___d426,
       mantissa_res_non_normalised_6_BIT_87_00_AND_NO_ETC___d429,
       mantissa_res_non_normalised_6_BIT_90_06_AND_NO_ETC___d432,
       mantissa_res_non_normalised_6_BIT_93_12_AND_NO_ETC___d435,
       mantissa_res_non_normalised_6_BIT_96_18_AND_NO_ETC___d438,
       mantissa_res_non_normalised_6_BIT_99_24_AND_NO_ETC___d441,
       mantissa_res_non_normalised_6_BIT_9_4_AND_NOT__ETC___d351;

  // action method put_A
  assign RDY_put_A = !got_A ;
  assign CAN_FIRE_put_A = !got_A ;
  assign WILL_FIRE_put_A = EN_put_A ;

  // action method put_B
  assign RDY_put_B = !got_B ;
  assign CAN_FIRE_put_B = !got_B ;
  assign WILL_FIRE_put_B = EN_put_B ;

  // actionvalue method get_res
  assign get_res = answer ;
  assign RDY_get_res = got_final && got_A && got_B ;
  assign CAN_FIRE_get_res = got_final && got_A && got_B ;
  assign WILL_FIRE_get_res = EN_get_res ;

  // rule RL_finalResult
  assign CAN_FIRE_RL_finalResult = stage3 ;
  assign WILL_FIRE_RL_finalResult = stage3 ;

  // rule RL_mantissaNormalisation
  assign CAN_FIRE_RL_mantissaNormalisation = stage2 ;
  assign WILL_FIRE_RL_mantissaNormalisation = stage2 ;

  // rule RL_exponentNormalisation
  assign CAN_FIRE_RL_exponentNormalisation = stage1 ;
  assign WILL_FIRE_RL_exponentNormalisation = stage1 ;

  // rule RL_preprocessing
  assign CAN_FIRE_RL_preprocessing = got_A && got_B ;
  assign WILL_FIRE_RL_preprocessing = CAN_FIRE_RL_preprocessing ;

  // register answer
  assign answer$D_IN =
	     (input_1_64 == 64'b0 || input_2_64 == 64'b0) ? 64'b0 : x__h6362 ;
  assign answer$EN = stage3 ;

  // register exponent_res_normalised_1
  assign exponent_res_normalised_1$D_IN =
	     exponent_res_overbiased_1 - 12'b001111111111 ;
  assign exponent_res_normalised_1$EN = stage1 ;

  // register exponent_res_normalised_2
  assign exponent_res_normalised_2$D_IN =
	     exponent_res_normalised_1[10:0] - shif__h6137 ;
  assign exponent_res_normalised_2$EN = stage2 ;

  // register exponent_res_normalised_3
  assign exponent_res_normalised_3$D_IN = 11'h0 ;
  assign exponent_res_normalised_3$EN = 1'b0 ;

  // register exponent_res_overbiased_1
  assign exponent_res_overbiased_1$D_IN = x__h829 + y__h830 ;
  assign exponent_res_overbiased_1$EN = CAN_FIRE_RL_preprocessing ;

  // register exponent_res_overbiased_2
  assign exponent_res_overbiased_2$D_IN = 12'h0 ;
  assign exponent_res_overbiased_2$EN = 1'b0 ;

  // register got_A
  assign got_A$D_IN = 1'd1 ;
  assign got_A$EN = EN_put_A ;

  // register got_B
  assign got_B$D_IN = 1'd1 ;
  assign got_B$EN = EN_put_B ;

  // register got_final
  assign got_final$D_IN =
	     input_1_64 == 64'b0 || input_2_64 == 64'b0 || answer != 64'b0 ;
  assign got_final$EN = stage3 ;

  // register input_1_64
  assign input_1_64$D_IN = put_A_a_in ;
  assign input_1_64$EN = EN_put_A ;

  // register input_2_64
  assign input_2_64$D_IN = put_B_b_in ;
  assign input_2_64$EN = EN_put_B ;

  // register mantissa_A
  assign mantissa_A$D_IN = input_1_64[51:0] ;
  assign mantissa_A$EN = CAN_FIRE_RL_preprocessing ;

  // register mantissa_B
  assign mantissa_B$D_IN = input_2_64[51:0] ;
  assign mantissa_B$EN = CAN_FIRE_RL_preprocessing ;

  // register mantissa_res_non_normalised
  assign mantissa_res_non_normalised$D_IN =
	     _1_CONCAT_mantissa_A_9_0_MUL_1_CONCAT_mantissa__ETC___d23[105:0] ;
  assign mantissa_res_non_normalised$EN = stage1 ;

  // register mantissa_res_non_normalised_reduced
  assign mantissa_res_non_normalised_reduced$D_IN =
	     mantissa_res_non_normalised_SL_IF_mantissa_res_ETC__q1[105:54] ;
  assign mantissa_res_non_normalised_reduced$EN = stage2 ;

  // register mantissa_res_normalised
  assign mantissa_res_normalised$D_IN = 52'h0 ;
  assign mantissa_res_normalised$EN = 1'b0 ;

  // register sign_out
  assign sign_out$D_IN = input_1_64[63] ^ input_2_64[63] ;
  assign sign_out$EN = CAN_FIRE_RL_preprocessing ;

  // register stage1
  assign stage1$D_IN = 1'd1 ;
  assign stage1$EN = CAN_FIRE_RL_preprocessing ;

  // register stage2
  assign stage2$D_IN = 1'd1 ;
  assign stage2$EN = stage1 ;

  // register stage3
  assign stage3$D_IN = 1'd1 ;
  assign stage3$EN = stage2 ;

  // remaining internal signals
  assign IF_mantissa_res_non_normalised_6_BIT_101_28_AN_ETC___d450 =
	     (mantissa_res_non_normalised[101] &&
	      NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240) ?
	       32'd5 :
	       (mantissa_res_non_normalised_6_BIT_102_30_AND_N_ETC___d444 ?
		  32'd4 :
		  ((mantissa_res_non_normalised[103] &&
		    !mantissa_res_non_normalised[104] &&
		    !mantissa_res_non_normalised[105]) ?
		     32'd3 :
		     ((mantissa_res_non_normalised[104] &&
		       !mantissa_res_non_normalised[105]) ?
			32'd2 :
			32'd1))) ;
  assign IF_mantissa_res_non_normalised_6_BIT_101_28_AN_ETC___d559 =
	     (mantissa_res_non_normalised[101] &&
	      NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240) ?
	       11'd3 :
	       (mantissa_res_non_normalised_6_BIT_102_30_AND_N_ETC___d444 ?
		  11'd2 :
		  ((mantissa_res_non_normalised[103] &&
		    !mantissa_res_non_normalised[104] &&
		    !mantissa_res_non_normalised[105]) ?
		     11'd1 :
		     ((mantissa_res_non_normalised[104] &&
		       !mantissa_res_non_normalised[105]) ?
			11'd0 :
			11'd2047))) ;
  assign IF_mantissa_res_non_normalised_6_BIT_11_8_AND__ETC___d540 =
	     (mantissa_res_non_normalised[11] &&
	      NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330) ?
	       32'd95 :
	       (mantissa_res_non_normalised_6_BIT_12_0_AND_NOT_ETC___d354 ?
		  32'd94 :
		  ((mantissa_res_non_normalised[13] &&
		    !mantissa_res_non_normalised[14] &&
		    NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327) ?
		     32'd93 :
		     IF_mantissa_res_non_normalised_6_BIT_14_4_AND__ETC___d537)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_11_8_AND__ETC___d649 =
	     (mantissa_res_non_normalised[11] &&
	      NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330) ?
	       11'd93 :
	       (mantissa_res_non_normalised_6_BIT_12_0_AND_NOT_ETC___d354 ?
		  11'd92 :
		  ((mantissa_res_non_normalised[13] &&
		    !mantissa_res_non_normalised[14] &&
		    NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327) ?
		     11'd91 :
		     IF_mantissa_res_non_normalised_6_BIT_14_4_AND__ETC___d646)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_14_4_AND__ETC___d537 =
	     (mantissa_res_non_normalised[14] &&
	      NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327) ?
	       32'd92 :
	       (mantissa_res_non_normalised_6_BIT_15_6_AND_NOT_ETC___d357 ?
		  32'd91 :
		  ((mantissa_res_non_normalised[16] &&
		    !mantissa_res_non_normalised[17] &&
		    NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324) ?
		     32'd90 :
		     IF_mantissa_res_non_normalised_6_BIT_17_0_AND__ETC___d534)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_14_4_AND__ETC___d646 =
	     (mantissa_res_non_normalised[14] &&
	      NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327) ?
	       11'd90 :
	       (mantissa_res_non_normalised_6_BIT_15_6_AND_NOT_ETC___d357 ?
		  11'd89 :
		  ((mantissa_res_non_normalised[16] &&
		    !mantissa_res_non_normalised[17] &&
		    NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324) ?
		     11'd88 :
		     IF_mantissa_res_non_normalised_6_BIT_17_0_AND__ETC___d643)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_17_0_AND__ETC___d534 =
	     (mantissa_res_non_normalised[17] &&
	      NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324) ?
	       32'd89 :
	       (mantissa_res_non_normalised_6_BIT_18_2_AND_NOT_ETC___d360 ?
		  32'd88 :
		  ((mantissa_res_non_normalised[19] &&
		    !mantissa_res_non_normalised[20] &&
		    NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321) ?
		     32'd87 :
		     IF_mantissa_res_non_normalised_6_BIT_20_6_AND__ETC___d531)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_17_0_AND__ETC___d643 =
	     (mantissa_res_non_normalised[17] &&
	      NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324) ?
	       11'd87 :
	       (mantissa_res_non_normalised_6_BIT_18_2_AND_NOT_ETC___d360 ?
		  11'd86 :
		  ((mantissa_res_non_normalised[19] &&
		    !mantissa_res_non_normalised[20] &&
		    NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321) ?
		     11'd85 :
		     IF_mantissa_res_non_normalised_6_BIT_20_6_AND__ETC___d640)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_20_6_AND__ETC___d531 =
	     (mantissa_res_non_normalised[20] &&
	      NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321) ?
	       32'd86 :
	       (mantissa_res_non_normalised_6_BIT_21_8_AND_NOT_ETC___d363 ?
		  32'd85 :
		  ((mantissa_res_non_normalised[22] &&
		    !mantissa_res_non_normalised[23] &&
		    NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318) ?
		     32'd84 :
		     IF_mantissa_res_non_normalised_6_BIT_23_2_AND__ETC___d528)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_20_6_AND__ETC___d640 =
	     (mantissa_res_non_normalised[20] &&
	      NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321) ?
	       11'd84 :
	       (mantissa_res_non_normalised_6_BIT_21_8_AND_NOT_ETC___d363 ?
		  11'd83 :
		  ((mantissa_res_non_normalised[22] &&
		    !mantissa_res_non_normalised[23] &&
		    NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318) ?
		     11'd82 :
		     IF_mantissa_res_non_normalised_6_BIT_23_2_AND__ETC___d637)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_23_2_AND__ETC___d528 =
	     (mantissa_res_non_normalised[23] &&
	      NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318) ?
	       32'd83 :
	       (mantissa_res_non_normalised_6_BIT_24_4_AND_NOT_ETC___d366 ?
		  32'd82 :
		  ((mantissa_res_non_normalised[25] &&
		    !mantissa_res_non_normalised[26] &&
		    NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315) ?
		     32'd81 :
		     IF_mantissa_res_non_normalised_6_BIT_26_8_AND__ETC___d525)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_23_2_AND__ETC___d637 =
	     (mantissa_res_non_normalised[23] &&
	      NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318) ?
	       11'd81 :
	       (mantissa_res_non_normalised_6_BIT_24_4_AND_NOT_ETC___d366 ?
		  11'd80 :
		  ((mantissa_res_non_normalised[25] &&
		    !mantissa_res_non_normalised[26] &&
		    NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315) ?
		     11'd79 :
		     IF_mantissa_res_non_normalised_6_BIT_26_8_AND__ETC___d634)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_26_8_AND__ETC___d525 =
	     (mantissa_res_non_normalised[26] &&
	      NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315) ?
	       32'd80 :
	       (mantissa_res_non_normalised_6_BIT_27_0_AND_NOT_ETC___d369 ?
		  32'd79 :
		  ((mantissa_res_non_normalised[28] &&
		    !mantissa_res_non_normalised[29] &&
		    NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312) ?
		     32'd78 :
		     IF_mantissa_res_non_normalised_6_BIT_29_4_AND__ETC___d522)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_26_8_AND__ETC___d634 =
	     (mantissa_res_non_normalised[26] &&
	      NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315) ?
	       11'd78 :
	       (mantissa_res_non_normalised_6_BIT_27_0_AND_NOT_ETC___d369 ?
		  11'd77 :
		  ((mantissa_res_non_normalised[28] &&
		    !mantissa_res_non_normalised[29] &&
		    NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312) ?
		     11'd76 :
		     IF_mantissa_res_non_normalised_6_BIT_29_4_AND__ETC___d631)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_29_4_AND__ETC___d522 =
	     (mantissa_res_non_normalised[29] &&
	      NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312) ?
	       32'd77 :
	       (mantissa_res_non_normalised_6_BIT_30_6_AND_NOT_ETC___d372 ?
		  32'd76 :
		  ((mantissa_res_non_normalised[31] &&
		    !mantissa_res_non_normalised[32] &&
		    NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309) ?
		     32'd75 :
		     IF_mantissa_res_non_normalised_6_BIT_32_0_AND__ETC___d519)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_29_4_AND__ETC___d631 =
	     (mantissa_res_non_normalised[29] &&
	      NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312) ?
	       11'd75 :
	       (mantissa_res_non_normalised_6_BIT_30_6_AND_NOT_ETC___d372 ?
		  11'd74 :
		  ((mantissa_res_non_normalised[31] &&
		    !mantissa_res_non_normalised[32] &&
		    NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309) ?
		     11'd73 :
		     IF_mantissa_res_non_normalised_6_BIT_32_0_AND__ETC___d628)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_2_0_AND_N_ETC___d549 =
	     (mantissa_res_non_normalised[2] &&
	      NOT_mantissa_res_non_normalised_6_BIT_3_2_3_AN_ETC___d339) ?
	       32'd104 :
	       (mantissa_res_non_normalised_6_BIT_3_2_AND_NOT__ETC___d345 ?
		  32'd103 :
		  ((mantissa_res_non_normalised[4] &&
		    !mantissa_res_non_normalised[5] &&
		    NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336) ?
		     32'd102 :
		     IF_mantissa_res_non_normalised_6_BIT_5_6_AND_N_ETC___d546)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_2_0_AND_N_ETC___d658 =
	     (mantissa_res_non_normalised[2] &&
	      NOT_mantissa_res_non_normalised_6_BIT_3_2_3_AN_ETC___d339) ?
	       11'd102 :
	       (mantissa_res_non_normalised_6_BIT_3_2_AND_NOT__ETC___d345 ?
		  11'd101 :
		  ((mantissa_res_non_normalised[4] &&
		    !mantissa_res_non_normalised[5] &&
		    NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336) ?
		     11'd100 :
		     IF_mantissa_res_non_normalised_6_BIT_5_6_AND_N_ETC___d655)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_32_0_AND__ETC___d519 =
	     (mantissa_res_non_normalised[32] &&
	      NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309) ?
	       32'd74 :
	       (mantissa_res_non_normalised_6_BIT_33_2_AND_NOT_ETC___d375 ?
		  32'd73 :
		  ((mantissa_res_non_normalised[34] &&
		    !mantissa_res_non_normalised[35] &&
		    NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306) ?
		     32'd72 :
		     IF_mantissa_res_non_normalised_6_BIT_35_6_AND__ETC___d516)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_32_0_AND__ETC___d628 =
	     (mantissa_res_non_normalised[32] &&
	      NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309) ?
	       11'd72 :
	       (mantissa_res_non_normalised_6_BIT_33_2_AND_NOT_ETC___d375 ?
		  11'd71 :
		  ((mantissa_res_non_normalised[34] &&
		    !mantissa_res_non_normalised[35] &&
		    NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306) ?
		     11'd70 :
		     IF_mantissa_res_non_normalised_6_BIT_35_6_AND__ETC___d625)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_35_6_AND__ETC___d516 =
	     (mantissa_res_non_normalised[35] &&
	      NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306) ?
	       32'd71 :
	       (mantissa_res_non_normalised_6_BIT_36_8_AND_NOT_ETC___d378 ?
		  32'd70 :
		  ((mantissa_res_non_normalised[37] &&
		    !mantissa_res_non_normalised[38] &&
		    NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303) ?
		     32'd69 :
		     IF_mantissa_res_non_normalised_6_BIT_38_02_AND_ETC___d513)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_35_6_AND__ETC___d625 =
	     (mantissa_res_non_normalised[35] &&
	      NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306) ?
	       11'd69 :
	       (mantissa_res_non_normalised_6_BIT_36_8_AND_NOT_ETC___d378 ?
		  11'd68 :
		  ((mantissa_res_non_normalised[37] &&
		    !mantissa_res_non_normalised[38] &&
		    NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303) ?
		     11'd67 :
		     IF_mantissa_res_non_normalised_6_BIT_38_02_AND_ETC___d622)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_38_02_AND_ETC___d513 =
	     (mantissa_res_non_normalised[38] &&
	      NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303) ?
	       32'd68 :
	       (mantissa_res_non_normalised_6_BIT_39_04_AND_NO_ETC___d381 ?
		  32'd67 :
		  ((mantissa_res_non_normalised[40] &&
		    !mantissa_res_non_normalised[41] &&
		    NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300) ?
		     32'd66 :
		     IF_mantissa_res_non_normalised_6_BIT_41_08_AND_ETC___d510)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_38_02_AND_ETC___d622 =
	     (mantissa_res_non_normalised[38] &&
	      NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303) ?
	       11'd66 :
	       (mantissa_res_non_normalised_6_BIT_39_04_AND_NO_ETC___d381 ?
		  11'd65 :
		  ((mantissa_res_non_normalised[40] &&
		    !mantissa_res_non_normalised[41] &&
		    NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300) ?
		     11'd64 :
		     IF_mantissa_res_non_normalised_6_BIT_41_08_AND_ETC___d619)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_41_08_AND_ETC___d510 =
	     (mantissa_res_non_normalised[41] &&
	      NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300) ?
	       32'd65 :
	       (mantissa_res_non_normalised_6_BIT_42_10_AND_NO_ETC___d384 ?
		  32'd64 :
		  ((mantissa_res_non_normalised[43] &&
		    !mantissa_res_non_normalised[44] &&
		    NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297) ?
		     32'd63 :
		     IF_mantissa_res_non_normalised_6_BIT_44_14_AND_ETC___d507)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_41_08_AND_ETC___d619 =
	     (mantissa_res_non_normalised[41] &&
	      NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300) ?
	       11'd63 :
	       (mantissa_res_non_normalised_6_BIT_42_10_AND_NO_ETC___d384 ?
		  11'd62 :
		  ((mantissa_res_non_normalised[43] &&
		    !mantissa_res_non_normalised[44] &&
		    NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297) ?
		     11'd61 :
		     IF_mantissa_res_non_normalised_6_BIT_44_14_AND_ETC___d616)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_44_14_AND_ETC___d507 =
	     (mantissa_res_non_normalised[44] &&
	      NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297) ?
	       32'd62 :
	       (mantissa_res_non_normalised_6_BIT_45_16_AND_NO_ETC___d387 ?
		  32'd61 :
		  ((mantissa_res_non_normalised[46] &&
		    !mantissa_res_non_normalised[47] &&
		    NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294) ?
		     32'd60 :
		     IF_mantissa_res_non_normalised_6_BIT_47_20_AND_ETC___d504)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_44_14_AND_ETC___d616 =
	     (mantissa_res_non_normalised[44] &&
	      NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297) ?
	       11'd60 :
	       (mantissa_res_non_normalised_6_BIT_45_16_AND_NO_ETC___d387 ?
		  11'd59 :
		  ((mantissa_res_non_normalised[46] &&
		    !mantissa_res_non_normalised[47] &&
		    NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294) ?
		     11'd58 :
		     IF_mantissa_res_non_normalised_6_BIT_47_20_AND_ETC___d613)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_47_20_AND_ETC___d504 =
	     (mantissa_res_non_normalised[47] &&
	      NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294) ?
	       32'd59 :
	       (mantissa_res_non_normalised_6_BIT_48_22_AND_NO_ETC___d390 ?
		  32'd58 :
		  ((mantissa_res_non_normalised[49] &&
		    !mantissa_res_non_normalised[50] &&
		    NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291) ?
		     32'd57 :
		     IF_mantissa_res_non_normalised_6_BIT_50_26_AND_ETC___d501)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_47_20_AND_ETC___d613 =
	     (mantissa_res_non_normalised[47] &&
	      NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294) ?
	       11'd57 :
	       (mantissa_res_non_normalised_6_BIT_48_22_AND_NO_ETC___d390 ?
		  11'd56 :
		  ((mantissa_res_non_normalised[49] &&
		    !mantissa_res_non_normalised[50] &&
		    NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291) ?
		     11'd55 :
		     IF_mantissa_res_non_normalised_6_BIT_50_26_AND_ETC___d610)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_50_26_AND_ETC___d501 =
	     (mantissa_res_non_normalised[50] &&
	      NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291) ?
	       32'd56 :
	       (mantissa_res_non_normalised_6_BIT_51_28_AND_NO_ETC___d393 ?
		  32'd55 :
		  ((mantissa_res_non_normalised[52] &&
		    !mantissa_res_non_normalised[53] &&
		    NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288) ?
		     32'd54 :
		     IF_mantissa_res_non_normalised_6_BIT_53_32_AND_ETC___d498)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_50_26_AND_ETC___d610 =
	     (mantissa_res_non_normalised[50] &&
	      NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291) ?
	       11'd54 :
	       (mantissa_res_non_normalised_6_BIT_51_28_AND_NO_ETC___d393 ?
		  11'd53 :
		  ((mantissa_res_non_normalised[52] &&
		    !mantissa_res_non_normalised[53] &&
		    NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288) ?
		     11'd52 :
		     IF_mantissa_res_non_normalised_6_BIT_53_32_AND_ETC___d607)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_53_32_AND_ETC___d498 =
	     (mantissa_res_non_normalised[53] &&
	      NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288) ?
	       32'd53 :
	       (mantissa_res_non_normalised_6_BIT_54_34_AND_NO_ETC___d396 ?
		  32'd52 :
		  ((mantissa_res_non_normalised[55] &&
		    !mantissa_res_non_normalised[56] &&
		    NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285) ?
		     32'd51 :
		     IF_mantissa_res_non_normalised_6_BIT_56_38_AND_ETC___d495)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_53_32_AND_ETC___d607 =
	     (mantissa_res_non_normalised[53] &&
	      NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288) ?
	       11'd51 :
	       (mantissa_res_non_normalised_6_BIT_54_34_AND_NO_ETC___d396 ?
		  11'd50 :
		  ((mantissa_res_non_normalised[55] &&
		    !mantissa_res_non_normalised[56] &&
		    NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285) ?
		     11'd49 :
		     IF_mantissa_res_non_normalised_6_BIT_56_38_AND_ETC___d604)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_56_38_AND_ETC___d495 =
	     (mantissa_res_non_normalised[56] &&
	      NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285) ?
	       32'd50 :
	       (mantissa_res_non_normalised_6_BIT_57_40_AND_NO_ETC___d399 ?
		  32'd49 :
		  ((mantissa_res_non_normalised[58] &&
		    !mantissa_res_non_normalised[59] &&
		    NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282) ?
		     32'd48 :
		     IF_mantissa_res_non_normalised_6_BIT_59_44_AND_ETC___d492)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_56_38_AND_ETC___d604 =
	     (mantissa_res_non_normalised[56] &&
	      NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285) ?
	       11'd48 :
	       (mantissa_res_non_normalised_6_BIT_57_40_AND_NO_ETC___d399 ?
		  11'd47 :
		  ((mantissa_res_non_normalised[58] &&
		    !mantissa_res_non_normalised[59] &&
		    NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282) ?
		     11'd46 :
		     IF_mantissa_res_non_normalised_6_BIT_59_44_AND_ETC___d601)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_59_44_AND_ETC___d492 =
	     (mantissa_res_non_normalised[59] &&
	      NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282) ?
	       32'd47 :
	       (mantissa_res_non_normalised_6_BIT_60_46_AND_NO_ETC___d402 ?
		  32'd46 :
		  ((mantissa_res_non_normalised[61] &&
		    !mantissa_res_non_normalised[62] &&
		    NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279) ?
		     32'd45 :
		     IF_mantissa_res_non_normalised_6_BIT_62_50_AND_ETC___d489)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_59_44_AND_ETC___d601 =
	     (mantissa_res_non_normalised[59] &&
	      NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282) ?
	       11'd45 :
	       (mantissa_res_non_normalised_6_BIT_60_46_AND_NO_ETC___d402 ?
		  11'd44 :
		  ((mantissa_res_non_normalised[61] &&
		    !mantissa_res_non_normalised[62] &&
		    NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279) ?
		     11'd43 :
		     IF_mantissa_res_non_normalised_6_BIT_62_50_AND_ETC___d598)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_5_6_AND_N_ETC___d546 =
	     (mantissa_res_non_normalised[5] &&
	      NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336) ?
	       32'd101 :
	       (mantissa_res_non_normalised_6_BIT_6_8_AND_NOT__ETC___d348 ?
		  32'd100 :
		  ((mantissa_res_non_normalised[7] &&
		    !mantissa_res_non_normalised[8] &&
		    NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333) ?
		     32'd99 :
		     IF_mantissa_res_non_normalised_6_BIT_8_2_AND_N_ETC___d543)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_5_6_AND_N_ETC___d655 =
	     (mantissa_res_non_normalised[5] &&
	      NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336) ?
	       11'd99 :
	       (mantissa_res_non_normalised_6_BIT_6_8_AND_NOT__ETC___d348 ?
		  11'd98 :
		  ((mantissa_res_non_normalised[7] &&
		    !mantissa_res_non_normalised[8] &&
		    NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333) ?
		     11'd97 :
		     IF_mantissa_res_non_normalised_6_BIT_8_2_AND_N_ETC___d652)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_62_50_AND_ETC___d489 =
	     (mantissa_res_non_normalised[62] &&
	      NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279) ?
	       32'd44 :
	       (mantissa_res_non_normalised_6_BIT_63_52_AND_NO_ETC___d405 ?
		  32'd43 :
		  ((mantissa_res_non_normalised[64] &&
		    !mantissa_res_non_normalised[65] &&
		    NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276) ?
		     32'd42 :
		     IF_mantissa_res_non_normalised_6_BIT_65_56_AND_ETC___d486)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_62_50_AND_ETC___d598 =
	     (mantissa_res_non_normalised[62] &&
	      NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279) ?
	       11'd42 :
	       (mantissa_res_non_normalised_6_BIT_63_52_AND_NO_ETC___d405 ?
		  11'd41 :
		  ((mantissa_res_non_normalised[64] &&
		    !mantissa_res_non_normalised[65] &&
		    NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276) ?
		     11'd40 :
		     IF_mantissa_res_non_normalised_6_BIT_65_56_AND_ETC___d595)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_65_56_AND_ETC___d486 =
	     (mantissa_res_non_normalised[65] &&
	      NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276) ?
	       32'd41 :
	       (mantissa_res_non_normalised_6_BIT_66_58_AND_NO_ETC___d408 ?
		  32'd40 :
		  ((mantissa_res_non_normalised[67] &&
		    !mantissa_res_non_normalised[68] &&
		    NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273) ?
		     32'd39 :
		     IF_mantissa_res_non_normalised_6_BIT_68_62_AND_ETC___d483)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_65_56_AND_ETC___d595 =
	     (mantissa_res_non_normalised[65] &&
	      NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276) ?
	       11'd39 :
	       (mantissa_res_non_normalised_6_BIT_66_58_AND_NO_ETC___d408 ?
		  11'd38 :
		  ((mantissa_res_non_normalised[67] &&
		    !mantissa_res_non_normalised[68] &&
		    NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273) ?
		     11'd37 :
		     IF_mantissa_res_non_normalised_6_BIT_68_62_AND_ETC___d592)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_68_62_AND_ETC___d483 =
	     (mantissa_res_non_normalised[68] &&
	      NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273) ?
	       32'd38 :
	       (mantissa_res_non_normalised_6_BIT_69_64_AND_NO_ETC___d411 ?
		  32'd37 :
		  ((mantissa_res_non_normalised[70] &&
		    !mantissa_res_non_normalised[71] &&
		    NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270) ?
		     32'd36 :
		     IF_mantissa_res_non_normalised_6_BIT_71_68_AND_ETC___d480)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_68_62_AND_ETC___d592 =
	     (mantissa_res_non_normalised[68] &&
	      NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273) ?
	       11'd36 :
	       (mantissa_res_non_normalised_6_BIT_69_64_AND_NO_ETC___d411 ?
		  11'd35 :
		  ((mantissa_res_non_normalised[70] &&
		    !mantissa_res_non_normalised[71] &&
		    NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270) ?
		     11'd34 :
		     IF_mantissa_res_non_normalised_6_BIT_71_68_AND_ETC___d589)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_71_68_AND_ETC___d480 =
	     (mantissa_res_non_normalised[71] &&
	      NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270) ?
	       32'd35 :
	       (mantissa_res_non_normalised_6_BIT_72_70_AND_NO_ETC___d414 ?
		  32'd34 :
		  ((mantissa_res_non_normalised[73] &&
		    !mantissa_res_non_normalised[74] &&
		    NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267) ?
		     32'd33 :
		     IF_mantissa_res_non_normalised_6_BIT_74_74_AND_ETC___d477)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_71_68_AND_ETC___d589 =
	     (mantissa_res_non_normalised[71] &&
	      NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270) ?
	       11'd33 :
	       (mantissa_res_non_normalised_6_BIT_72_70_AND_NO_ETC___d414 ?
		  11'd32 :
		  ((mantissa_res_non_normalised[73] &&
		    !mantissa_res_non_normalised[74] &&
		    NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267) ?
		     11'd31 :
		     IF_mantissa_res_non_normalised_6_BIT_74_74_AND_ETC___d586)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_74_74_AND_ETC___d477 =
	     (mantissa_res_non_normalised[74] &&
	      NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267) ?
	       32'd32 :
	       (mantissa_res_non_normalised_6_BIT_75_76_AND_NO_ETC___d417 ?
		  32'd31 :
		  ((mantissa_res_non_normalised[76] &&
		    !mantissa_res_non_normalised[77] &&
		    NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264) ?
		     32'd30 :
		     IF_mantissa_res_non_normalised_6_BIT_77_80_AND_ETC___d474)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_74_74_AND_ETC___d586 =
	     (mantissa_res_non_normalised[74] &&
	      NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267) ?
	       11'd30 :
	       (mantissa_res_non_normalised_6_BIT_75_76_AND_NO_ETC___d417 ?
		  11'd29 :
		  ((mantissa_res_non_normalised[76] &&
		    !mantissa_res_non_normalised[77] &&
		    NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264) ?
		     11'd28 :
		     IF_mantissa_res_non_normalised_6_BIT_77_80_AND_ETC___d583)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_77_80_AND_ETC___d474 =
	     (mantissa_res_non_normalised[77] &&
	      NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264) ?
	       32'd29 :
	       (mantissa_res_non_normalised_6_BIT_78_82_AND_NO_ETC___d420 ?
		  32'd28 :
		  ((mantissa_res_non_normalised[79] &&
		    !mantissa_res_non_normalised[80] &&
		    NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261) ?
		     32'd27 :
		     IF_mantissa_res_non_normalised_6_BIT_80_86_AND_ETC___d471)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_77_80_AND_ETC___d583 =
	     (mantissa_res_non_normalised[77] &&
	      NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264) ?
	       11'd27 :
	       (mantissa_res_non_normalised_6_BIT_78_82_AND_NO_ETC___d420 ?
		  11'd26 :
		  ((mantissa_res_non_normalised[79] &&
		    !mantissa_res_non_normalised[80] &&
		    NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261) ?
		     11'd25 :
		     IF_mantissa_res_non_normalised_6_BIT_80_86_AND_ETC___d580)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_80_86_AND_ETC___d471 =
	     (mantissa_res_non_normalised[80] &&
	      NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261) ?
	       32'd26 :
	       (mantissa_res_non_normalised_6_BIT_81_88_AND_NO_ETC___d423 ?
		  32'd25 :
		  ((mantissa_res_non_normalised[82] &&
		    !mantissa_res_non_normalised[83] &&
		    NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258) ?
		     32'd24 :
		     IF_mantissa_res_non_normalised_6_BIT_83_92_AND_ETC___d468)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_80_86_AND_ETC___d580 =
	     (mantissa_res_non_normalised[80] &&
	      NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261) ?
	       11'd24 :
	       (mantissa_res_non_normalised_6_BIT_81_88_AND_NO_ETC___d423 ?
		  11'd23 :
		  ((mantissa_res_non_normalised[82] &&
		    !mantissa_res_non_normalised[83] &&
		    NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258) ?
		     11'd22 :
		     IF_mantissa_res_non_normalised_6_BIT_83_92_AND_ETC___d577)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_83_92_AND_ETC___d468 =
	     (mantissa_res_non_normalised[83] &&
	      NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258) ?
	       32'd23 :
	       (mantissa_res_non_normalised_6_BIT_84_94_AND_NO_ETC___d426 ?
		  32'd22 :
		  ((mantissa_res_non_normalised[85] &&
		    !mantissa_res_non_normalised[86] &&
		    NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255) ?
		     32'd21 :
		     IF_mantissa_res_non_normalised_6_BIT_86_98_AND_ETC___d465)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_83_92_AND_ETC___d577 =
	     (mantissa_res_non_normalised[83] &&
	      NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258) ?
	       11'd21 :
	       (mantissa_res_non_normalised_6_BIT_84_94_AND_NO_ETC___d426 ?
		  11'd20 :
		  ((mantissa_res_non_normalised[85] &&
		    !mantissa_res_non_normalised[86] &&
		    NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255) ?
		     11'd19 :
		     IF_mantissa_res_non_normalised_6_BIT_86_98_AND_ETC___d574)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_86_98_AND_ETC___d465 =
	     (mantissa_res_non_normalised[86] &&
	      NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255) ?
	       32'd20 :
	       (mantissa_res_non_normalised_6_BIT_87_00_AND_NO_ETC___d429 ?
		  32'd19 :
		  ((mantissa_res_non_normalised[88] &&
		    !mantissa_res_non_normalised[89] &&
		    NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252) ?
		     32'd18 :
		     IF_mantissa_res_non_normalised_6_BIT_89_04_AND_ETC___d462)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_86_98_AND_ETC___d574 =
	     (mantissa_res_non_normalised[86] &&
	      NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255) ?
	       11'd18 :
	       (mantissa_res_non_normalised_6_BIT_87_00_AND_NO_ETC___d429 ?
		  11'd17 :
		  ((mantissa_res_non_normalised[88] &&
		    !mantissa_res_non_normalised[89] &&
		    NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252) ?
		     11'd16 :
		     IF_mantissa_res_non_normalised_6_BIT_89_04_AND_ETC___d571)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_89_04_AND_ETC___d462 =
	     (mantissa_res_non_normalised[89] &&
	      NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252) ?
	       32'd17 :
	       (mantissa_res_non_normalised_6_BIT_90_06_AND_NO_ETC___d432 ?
		  32'd16 :
		  ((mantissa_res_non_normalised[91] &&
		    !mantissa_res_non_normalised[92] &&
		    NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249) ?
		     32'd15 :
		     IF_mantissa_res_non_normalised_6_BIT_92_10_AND_ETC___d459)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_89_04_AND_ETC___d571 =
	     (mantissa_res_non_normalised[89] &&
	      NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252) ?
	       11'd15 :
	       (mantissa_res_non_normalised_6_BIT_90_06_AND_NO_ETC___d432 ?
		  11'd14 :
		  ((mantissa_res_non_normalised[91] &&
		    !mantissa_res_non_normalised[92] &&
		    NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249) ?
		     11'd13 :
		     IF_mantissa_res_non_normalised_6_BIT_92_10_AND_ETC___d568)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_8_2_AND_N_ETC___d543 =
	     (mantissa_res_non_normalised[8] &&
	      NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333) ?
	       32'd98 :
	       (mantissa_res_non_normalised_6_BIT_9_4_AND_NOT__ETC___d351 ?
		  32'd97 :
		  ((mantissa_res_non_normalised[10] &&
		    !mantissa_res_non_normalised[11] &&
		    NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330) ?
		     32'd96 :
		     IF_mantissa_res_non_normalised_6_BIT_11_8_AND__ETC___d540)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_8_2_AND_N_ETC___d652 =
	     (mantissa_res_non_normalised[8] &&
	      NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333) ?
	       11'd96 :
	       (mantissa_res_non_normalised_6_BIT_9_4_AND_NOT__ETC___d351 ?
		  11'd95 :
		  ((mantissa_res_non_normalised[10] &&
		    !mantissa_res_non_normalised[11] &&
		    NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330) ?
		     11'd94 :
		     IF_mantissa_res_non_normalised_6_BIT_11_8_AND__ETC___d649)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_92_10_AND_ETC___d459 =
	     (mantissa_res_non_normalised[92] &&
	      NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249) ?
	       32'd14 :
	       (mantissa_res_non_normalised_6_BIT_93_12_AND_NO_ETC___d435 ?
		  32'd13 :
		  ((mantissa_res_non_normalised[94] &&
		    !mantissa_res_non_normalised[95] &&
		    NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246) ?
		     32'd12 :
		     IF_mantissa_res_non_normalised_6_BIT_95_16_AND_ETC___d456)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_92_10_AND_ETC___d568 =
	     (mantissa_res_non_normalised[92] &&
	      NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249) ?
	       11'd12 :
	       (mantissa_res_non_normalised_6_BIT_93_12_AND_NO_ETC___d435 ?
		  11'd11 :
		  ((mantissa_res_non_normalised[94] &&
		    !mantissa_res_non_normalised[95] &&
		    NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246) ?
		     11'd10 :
		     IF_mantissa_res_non_normalised_6_BIT_95_16_AND_ETC___d565)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_95_16_AND_ETC___d456 =
	     (mantissa_res_non_normalised[95] &&
	      NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246) ?
	       32'd11 :
	       (mantissa_res_non_normalised_6_BIT_96_18_AND_NO_ETC___d438 ?
		  32'd10 :
		  ((mantissa_res_non_normalised[97] &&
		    !mantissa_res_non_normalised[98] &&
		    NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243) ?
		     32'd9 :
		     IF_mantissa_res_non_normalised_6_BIT_98_22_AND_ETC___d453)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_95_16_AND_ETC___d565 =
	     (mantissa_res_non_normalised[95] &&
	      NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246) ?
	       11'd9 :
	       (mantissa_res_non_normalised_6_BIT_96_18_AND_NO_ETC___d438 ?
		  11'd8 :
		  ((mantissa_res_non_normalised[97] &&
		    !mantissa_res_non_normalised[98] &&
		    NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243) ?
		     11'd7 :
		     IF_mantissa_res_non_normalised_6_BIT_98_22_AND_ETC___d562)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_98_22_AND_ETC___d453 =
	     (mantissa_res_non_normalised[98] &&
	      NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243) ?
	       32'd8 :
	       (mantissa_res_non_normalised_6_BIT_99_24_AND_NO_ETC___d441 ?
		  32'd7 :
		  ((mantissa_res_non_normalised[100] &&
		    !mantissa_res_non_normalised[101] &&
		    NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240) ?
		     32'd6 :
		     IF_mantissa_res_non_normalised_6_BIT_101_28_AN_ETC___d450)) ;
  assign IF_mantissa_res_non_normalised_6_BIT_98_22_AND_ETC___d562 =
	     (mantissa_res_non_normalised[98] &&
	      NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243) ?
	       11'd6 :
	       (mantissa_res_non_normalised_6_BIT_99_24_AND_NO_ETC___d441 ?
		  11'd5 :
		  ((mantissa_res_non_normalised[100] &&
		    !mantissa_res_non_normalised[101] &&
		    NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240) ?
		     11'd4 :
		     IF_mantissa_res_non_normalised_6_BIT_101_28_AN_ETC___d559)) ;
  assign NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240 =
	     !mantissa_res_non_normalised[102] &&
	     !mantissa_res_non_normalised[103] &&
	     !mantissa_res_non_normalised[104] &&
	     !mantissa_res_non_normalised[105] ;
  assign NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330 =
	     !mantissa_res_non_normalised[12] &&
	     !mantissa_res_non_normalised[13] &&
	     !mantissa_res_non_normalised[14] &&
	     NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327 =
	     !mantissa_res_non_normalised[15] &&
	     !mantissa_res_non_normalised[16] &&
	     !mantissa_res_non_normalised[17] &&
	     NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324 =
	     !mantissa_res_non_normalised[18] &&
	     !mantissa_res_non_normalised[19] &&
	     !mantissa_res_non_normalised[20] &&
	     NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321 =
	     !mantissa_res_non_normalised[21] &&
	     !mantissa_res_non_normalised[22] &&
	     !mantissa_res_non_normalised[23] &&
	     NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318 =
	     !mantissa_res_non_normalised[24] &&
	     !mantissa_res_non_normalised[25] &&
	     !mantissa_res_non_normalised[26] &&
	     NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315 =
	     !mantissa_res_non_normalised[27] &&
	     !mantissa_res_non_normalised[28] &&
	     !mantissa_res_non_normalised[29] &&
	     NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312 =
	     !mantissa_res_non_normalised[30] &&
	     !mantissa_res_non_normalised[31] &&
	     !mantissa_res_non_normalised[32] &&
	     NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309 =
	     !mantissa_res_non_normalised[33] &&
	     !mantissa_res_non_normalised[34] &&
	     !mantissa_res_non_normalised[35] &&
	     NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306 =
	     !mantissa_res_non_normalised[36] &&
	     !mantissa_res_non_normalised[37] &&
	     !mantissa_res_non_normalised[38] &&
	     NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303 =
	     !mantissa_res_non_normalised[39] &&
	     !mantissa_res_non_normalised[40] &&
	     !mantissa_res_non_normalised[41] &&
	     NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_3_2_3_AN_ETC___d339 =
	     !mantissa_res_non_normalised[3] &&
	     !mantissa_res_non_normalised[4] &&
	     !mantissa_res_non_normalised[5] &&
	     NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300 =
	     !mantissa_res_non_normalised[42] &&
	     !mantissa_res_non_normalised[43] &&
	     !mantissa_res_non_normalised[44] &&
	     NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297 =
	     !mantissa_res_non_normalised[45] &&
	     !mantissa_res_non_normalised[46] &&
	     !mantissa_res_non_normalised[47] &&
	     NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294 =
	     !mantissa_res_non_normalised[48] &&
	     !mantissa_res_non_normalised[49] &&
	     !mantissa_res_non_normalised[50] &&
	     NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291 =
	     !mantissa_res_non_normalised[51] &&
	     !mantissa_res_non_normalised[52] &&
	     !mantissa_res_non_normalised[53] &&
	     NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288 =
	     !mantissa_res_non_normalised[54] &&
	     !mantissa_res_non_normalised[55] &&
	     !mantissa_res_non_normalised[56] &&
	     NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285 =
	     !mantissa_res_non_normalised[57] &&
	     !mantissa_res_non_normalised[58] &&
	     !mantissa_res_non_normalised[59] &&
	     NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282 =
	     !mantissa_res_non_normalised[60] &&
	     !mantissa_res_non_normalised[61] &&
	     !mantissa_res_non_normalised[62] &&
	     NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279 =
	     !mantissa_res_non_normalised[63] &&
	     !mantissa_res_non_normalised[64] &&
	     !mantissa_res_non_normalised[65] &&
	     NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276 =
	     !mantissa_res_non_normalised[66] &&
	     !mantissa_res_non_normalised[67] &&
	     !mantissa_res_non_normalised[68] &&
	     NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273 =
	     !mantissa_res_non_normalised[69] &&
	     !mantissa_res_non_normalised[70] &&
	     !mantissa_res_non_normalised[71] &&
	     NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336 =
	     !mantissa_res_non_normalised[6] &&
	     !mantissa_res_non_normalised[7] &&
	     !mantissa_res_non_normalised[8] &&
	     NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270 =
	     !mantissa_res_non_normalised[72] &&
	     !mantissa_res_non_normalised[73] &&
	     !mantissa_res_non_normalised[74] &&
	     NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267 =
	     !mantissa_res_non_normalised[75] &&
	     !mantissa_res_non_normalised[76] &&
	     !mantissa_res_non_normalised[77] &&
	     NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264 =
	     !mantissa_res_non_normalised[78] &&
	     !mantissa_res_non_normalised[79] &&
	     !mantissa_res_non_normalised[80] &&
	     NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261 =
	     !mantissa_res_non_normalised[81] &&
	     !mantissa_res_non_normalised[82] &&
	     !mantissa_res_non_normalised[83] &&
	     NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258 =
	     !mantissa_res_non_normalised[84] &&
	     !mantissa_res_non_normalised[85] &&
	     !mantissa_res_non_normalised[86] &&
	     NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255 =
	     !mantissa_res_non_normalised[87] &&
	     !mantissa_res_non_normalised[88] &&
	     !mantissa_res_non_normalised[89] &&
	     NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252 =
	     !mantissa_res_non_normalised[90] &&
	     !mantissa_res_non_normalised[91] &&
	     !mantissa_res_non_normalised[92] &&
	     NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249 =
	     !mantissa_res_non_normalised[93] &&
	     !mantissa_res_non_normalised[94] &&
	     !mantissa_res_non_normalised[95] &&
	     NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246 =
	     !mantissa_res_non_normalised[96] &&
	     !mantissa_res_non_normalised[97] &&
	     !mantissa_res_non_normalised[98] &&
	     NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243 =
	     !mantissa_res_non_normalised[99] &&
	     !mantissa_res_non_normalised[100] &&
	     !mantissa_res_non_normalised[101] &&
	     NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240 ;
  assign NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333 =
	     !mantissa_res_non_normalised[9] &&
	     !mantissa_res_non_normalised[10] &&
	     !mantissa_res_non_normalised[11] &&
	     NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330 ;
  assign _1_CONCAT_mantissa_A_9_0_MUL_1_CONCAT_mantissa__ETC___d23 =
	     { 54'd1, mantissa_A } * { 54'd1, mantissa_B } ;
  assign mantissa_res_non_normalised_6_BIT_0_7_AND_NOT__ETC___d342 =
	     mantissa_res_non_normalised[0] &&
	     !mantissa_res_non_normalised[1] &&
	     !mantissa_res_non_normalised[2] &&
	     NOT_mantissa_res_non_normalised_6_BIT_3_2_3_AN_ETC___d339 ;
  assign mantissa_res_non_normalised_6_BIT_102_30_AND_N_ETC___d444 =
	     mantissa_res_non_normalised[102] &&
	     !mantissa_res_non_normalised[103] &&
	     !mantissa_res_non_normalised[104] &&
	     !mantissa_res_non_normalised[105] ;
  assign mantissa_res_non_normalised_6_BIT_12_0_AND_NOT_ETC___d354 =
	     mantissa_res_non_normalised[12] &&
	     !mantissa_res_non_normalised[13] &&
	     !mantissa_res_non_normalised[14] &&
	     NOT_mantissa_res_non_normalised_6_BIT_15_6_7_A_ETC___d327 ;
  assign mantissa_res_non_normalised_6_BIT_15_6_AND_NOT_ETC___d357 =
	     mantissa_res_non_normalised[15] &&
	     !mantissa_res_non_normalised[16] &&
	     !mantissa_res_non_normalised[17] &&
	     NOT_mantissa_res_non_normalised_6_BIT_18_2_3_A_ETC___d324 ;
  assign mantissa_res_non_normalised_6_BIT_18_2_AND_NOT_ETC___d360 =
	     mantissa_res_non_normalised[18] &&
	     !mantissa_res_non_normalised[19] &&
	     !mantissa_res_non_normalised[20] &&
	     NOT_mantissa_res_non_normalised_6_BIT_21_8_9_A_ETC___d321 ;
  assign mantissa_res_non_normalised_6_BIT_21_8_AND_NOT_ETC___d363 =
	     mantissa_res_non_normalised[21] &&
	     !mantissa_res_non_normalised[22] &&
	     !mantissa_res_non_normalised[23] &&
	     NOT_mantissa_res_non_normalised_6_BIT_24_4_5_A_ETC___d318 ;
  assign mantissa_res_non_normalised_6_BIT_24_4_AND_NOT_ETC___d366 =
	     mantissa_res_non_normalised[24] &&
	     !mantissa_res_non_normalised[25] &&
	     !mantissa_res_non_normalised[26] &&
	     NOT_mantissa_res_non_normalised_6_BIT_27_0_1_A_ETC___d315 ;
  assign mantissa_res_non_normalised_6_BIT_27_0_AND_NOT_ETC___d369 =
	     mantissa_res_non_normalised[27] &&
	     !mantissa_res_non_normalised[28] &&
	     !mantissa_res_non_normalised[29] &&
	     NOT_mantissa_res_non_normalised_6_BIT_30_6_7_A_ETC___d312 ;
  assign mantissa_res_non_normalised_6_BIT_30_6_AND_NOT_ETC___d372 =
	     mantissa_res_non_normalised[30] &&
	     !mantissa_res_non_normalised[31] &&
	     !mantissa_res_non_normalised[32] &&
	     NOT_mantissa_res_non_normalised_6_BIT_33_2_3_A_ETC___d309 ;
  assign mantissa_res_non_normalised_6_BIT_33_2_AND_NOT_ETC___d375 =
	     mantissa_res_non_normalised[33] &&
	     !mantissa_res_non_normalised[34] &&
	     !mantissa_res_non_normalised[35] &&
	     NOT_mantissa_res_non_normalised_6_BIT_36_8_9_A_ETC___d306 ;
  assign mantissa_res_non_normalised_6_BIT_36_8_AND_NOT_ETC___d378 =
	     mantissa_res_non_normalised[36] &&
	     !mantissa_res_non_normalised[37] &&
	     !mantissa_res_non_normalised[38] &&
	     NOT_mantissa_res_non_normalised_6_BIT_39_04_05_ETC___d303 ;
  assign mantissa_res_non_normalised_6_BIT_39_04_AND_NO_ETC___d381 =
	     mantissa_res_non_normalised[39] &&
	     !mantissa_res_non_normalised[40] &&
	     !mantissa_res_non_normalised[41] &&
	     NOT_mantissa_res_non_normalised_6_BIT_42_10_11_ETC___d300 ;
  assign mantissa_res_non_normalised_6_BIT_3_2_AND_NOT__ETC___d345 =
	     mantissa_res_non_normalised[3] &&
	     !mantissa_res_non_normalised[4] &&
	     !mantissa_res_non_normalised[5] &&
	     NOT_mantissa_res_non_normalised_6_BIT_6_8_9_AN_ETC___d336 ;
  assign mantissa_res_non_normalised_6_BIT_42_10_AND_NO_ETC___d384 =
	     mantissa_res_non_normalised[42] &&
	     !mantissa_res_non_normalised[43] &&
	     !mantissa_res_non_normalised[44] &&
	     NOT_mantissa_res_non_normalised_6_BIT_45_16_17_ETC___d297 ;
  assign mantissa_res_non_normalised_6_BIT_45_16_AND_NO_ETC___d387 =
	     mantissa_res_non_normalised[45] &&
	     !mantissa_res_non_normalised[46] &&
	     !mantissa_res_non_normalised[47] &&
	     NOT_mantissa_res_non_normalised_6_BIT_48_22_23_ETC___d294 ;
  assign mantissa_res_non_normalised_6_BIT_48_22_AND_NO_ETC___d390 =
	     mantissa_res_non_normalised[48] &&
	     !mantissa_res_non_normalised[49] &&
	     !mantissa_res_non_normalised[50] &&
	     NOT_mantissa_res_non_normalised_6_BIT_51_28_29_ETC___d291 ;
  assign mantissa_res_non_normalised_6_BIT_51_28_AND_NO_ETC___d393 =
	     mantissa_res_non_normalised[51] &&
	     !mantissa_res_non_normalised[52] &&
	     !mantissa_res_non_normalised[53] &&
	     NOT_mantissa_res_non_normalised_6_BIT_54_34_35_ETC___d288 ;
  assign mantissa_res_non_normalised_6_BIT_54_34_AND_NO_ETC___d396 =
	     mantissa_res_non_normalised[54] &&
	     !mantissa_res_non_normalised[55] &&
	     !mantissa_res_non_normalised[56] &&
	     NOT_mantissa_res_non_normalised_6_BIT_57_40_41_ETC___d285 ;
  assign mantissa_res_non_normalised_6_BIT_57_40_AND_NO_ETC___d399 =
	     mantissa_res_non_normalised[57] &&
	     !mantissa_res_non_normalised[58] &&
	     !mantissa_res_non_normalised[59] &&
	     NOT_mantissa_res_non_normalised_6_BIT_60_46_47_ETC___d282 ;
  assign mantissa_res_non_normalised_6_BIT_60_46_AND_NO_ETC___d402 =
	     mantissa_res_non_normalised[60] &&
	     !mantissa_res_non_normalised[61] &&
	     !mantissa_res_non_normalised[62] &&
	     NOT_mantissa_res_non_normalised_6_BIT_63_52_53_ETC___d279 ;
  assign mantissa_res_non_normalised_6_BIT_63_52_AND_NO_ETC___d405 =
	     mantissa_res_non_normalised[63] &&
	     !mantissa_res_non_normalised[64] &&
	     !mantissa_res_non_normalised[65] &&
	     NOT_mantissa_res_non_normalised_6_BIT_66_58_59_ETC___d276 ;
  assign mantissa_res_non_normalised_6_BIT_66_58_AND_NO_ETC___d408 =
	     mantissa_res_non_normalised[66] &&
	     !mantissa_res_non_normalised[67] &&
	     !mantissa_res_non_normalised[68] &&
	     NOT_mantissa_res_non_normalised_6_BIT_69_64_65_ETC___d273 ;
  assign mantissa_res_non_normalised_6_BIT_69_64_AND_NO_ETC___d411 =
	     mantissa_res_non_normalised[69] &&
	     !mantissa_res_non_normalised[70] &&
	     !mantissa_res_non_normalised[71] &&
	     NOT_mantissa_res_non_normalised_6_BIT_72_70_71_ETC___d270 ;
  assign mantissa_res_non_normalised_6_BIT_6_8_AND_NOT__ETC___d348 =
	     mantissa_res_non_normalised[6] &&
	     !mantissa_res_non_normalised[7] &&
	     !mantissa_res_non_normalised[8] &&
	     NOT_mantissa_res_non_normalised_6_BIT_9_4_5_AN_ETC___d333 ;
  assign mantissa_res_non_normalised_6_BIT_72_70_AND_NO_ETC___d414 =
	     mantissa_res_non_normalised[72] &&
	     !mantissa_res_non_normalised[73] &&
	     !mantissa_res_non_normalised[74] &&
	     NOT_mantissa_res_non_normalised_6_BIT_75_76_77_ETC___d267 ;
  assign mantissa_res_non_normalised_6_BIT_75_76_AND_NO_ETC___d417 =
	     mantissa_res_non_normalised[75] &&
	     !mantissa_res_non_normalised[76] &&
	     !mantissa_res_non_normalised[77] &&
	     NOT_mantissa_res_non_normalised_6_BIT_78_82_83_ETC___d264 ;
  assign mantissa_res_non_normalised_6_BIT_78_82_AND_NO_ETC___d420 =
	     mantissa_res_non_normalised[78] &&
	     !mantissa_res_non_normalised[79] &&
	     !mantissa_res_non_normalised[80] &&
	     NOT_mantissa_res_non_normalised_6_BIT_81_88_89_ETC___d261 ;
  assign mantissa_res_non_normalised_6_BIT_81_88_AND_NO_ETC___d423 =
	     mantissa_res_non_normalised[81] &&
	     !mantissa_res_non_normalised[82] &&
	     !mantissa_res_non_normalised[83] &&
	     NOT_mantissa_res_non_normalised_6_BIT_84_94_95_ETC___d258 ;
  assign mantissa_res_non_normalised_6_BIT_84_94_AND_NO_ETC___d426 =
	     mantissa_res_non_normalised[84] &&
	     !mantissa_res_non_normalised[85] &&
	     !mantissa_res_non_normalised[86] &&
	     NOT_mantissa_res_non_normalised_6_BIT_87_00_01_ETC___d255 ;
  assign mantissa_res_non_normalised_6_BIT_87_00_AND_NO_ETC___d429 =
	     mantissa_res_non_normalised[87] &&
	     !mantissa_res_non_normalised[88] &&
	     !mantissa_res_non_normalised[89] &&
	     NOT_mantissa_res_non_normalised_6_BIT_90_06_07_ETC___d252 ;
  assign mantissa_res_non_normalised_6_BIT_90_06_AND_NO_ETC___d432 =
	     mantissa_res_non_normalised[90] &&
	     !mantissa_res_non_normalised[91] &&
	     !mantissa_res_non_normalised[92] &&
	     NOT_mantissa_res_non_normalised_6_BIT_93_12_13_ETC___d249 ;
  assign mantissa_res_non_normalised_6_BIT_93_12_AND_NO_ETC___d435 =
	     mantissa_res_non_normalised[93] &&
	     !mantissa_res_non_normalised[94] &&
	     !mantissa_res_non_normalised[95] &&
	     NOT_mantissa_res_non_normalised_6_BIT_96_18_19_ETC___d246 ;
  assign mantissa_res_non_normalised_6_BIT_96_18_AND_NO_ETC___d438 =
	     mantissa_res_non_normalised[96] &&
	     !mantissa_res_non_normalised[97] &&
	     !mantissa_res_non_normalised[98] &&
	     NOT_mantissa_res_non_normalised_6_BIT_99_24_25_ETC___d243 ;
  assign mantissa_res_non_normalised_6_BIT_99_24_AND_NO_ETC___d441 =
	     mantissa_res_non_normalised[99] &&
	     !mantissa_res_non_normalised[100] &&
	     !mantissa_res_non_normalised[101] &&
	     NOT_mantissa_res_non_normalised_6_BIT_102_30_3_ETC___d240 ;
  assign mantissa_res_non_normalised_6_BIT_9_4_AND_NOT__ETC___d351 =
	     mantissa_res_non_normalised[9] &&
	     !mantissa_res_non_normalised[10] &&
	     !mantissa_res_non_normalised[11] &&
	     NOT_mantissa_res_non_normalised_6_BIT_12_0_1_A_ETC___d330 ;
  assign mantissa_res_non_normalised_SL_IF_mantissa_res_ETC__q1 =
	     mantissa_res_non_normalised <<
	     (mantissa_res_non_normalised_6_BIT_0_7_AND_NOT__ETC___d342 ?
		32'd106 :
		((mantissa_res_non_normalised[1] &&
		  !mantissa_res_non_normalised[2] &&
		  NOT_mantissa_res_non_normalised_6_BIT_3_2_3_AN_ETC___d339) ?
		   32'd105 :
		   IF_mantissa_res_non_normalised_6_BIT_2_0_AND_N_ETC___d549)) ;
  assign shif__h6137 =
	     mantissa_res_non_normalised_6_BIT_0_7_AND_NOT__ETC___d342 ?
	       11'd104 :
	       ((mantissa_res_non_normalised[1] &&
		 !mantissa_res_non_normalised[2] &&
		 NOT_mantissa_res_non_normalised_6_BIT_3_2_3_AN_ETC___d339) ?
		  11'd103 :
		  IF_mantissa_res_non_normalised_6_BIT_2_0_AND_N_ETC___d658) ;
  assign x__h6362 =
	     { sign_out,
	       exponent_res_normalised_2,
	       mantissa_res_non_normalised_reduced } ;
  assign x__h829 = { 1'b0, input_1_64[62:52] } ;
  assign y__h830 = { 1'b0, input_2_64[62:52] } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        answer <= `BSV_ASSIGNMENT_DELAY 64'd0;
	exponent_res_normalised_1 <= `BSV_ASSIGNMENT_DELAY 12'd0;
	exponent_res_normalised_2 <= `BSV_ASSIGNMENT_DELAY 11'd0;
	exponent_res_normalised_3 <= `BSV_ASSIGNMENT_DELAY 11'd0;
	exponent_res_overbiased_1 <= `BSV_ASSIGNMENT_DELAY 12'd0;
	exponent_res_overbiased_2 <= `BSV_ASSIGNMENT_DELAY 12'd0;
	got_A <= `BSV_ASSIGNMENT_DELAY 1'd0;
	got_B <= `BSV_ASSIGNMENT_DELAY 1'd0;
	got_final <= `BSV_ASSIGNMENT_DELAY 1'd0;
	input_1_64 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	input_2_64 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mantissa_A <= `BSV_ASSIGNMENT_DELAY 52'd0;
	mantissa_B <= `BSV_ASSIGNMENT_DELAY 52'd0;
	mantissa_res_non_normalised <= `BSV_ASSIGNMENT_DELAY 106'd0;
	mantissa_res_non_normalised_reduced <= `BSV_ASSIGNMENT_DELAY 52'd0;
	mantissa_res_normalised <= `BSV_ASSIGNMENT_DELAY 52'd0;
	sign_out <= `BSV_ASSIGNMENT_DELAY 1'd0;
	stage1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	stage2 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	stage3 <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (answer$EN) answer <= `BSV_ASSIGNMENT_DELAY answer$D_IN;
	if (exponent_res_normalised_1$EN)
	  exponent_res_normalised_1 <= `BSV_ASSIGNMENT_DELAY
	      exponent_res_normalised_1$D_IN;
	if (exponent_res_normalised_2$EN)
	  exponent_res_normalised_2 <= `BSV_ASSIGNMENT_DELAY
	      exponent_res_normalised_2$D_IN;
	if (exponent_res_normalised_3$EN)
	  exponent_res_normalised_3 <= `BSV_ASSIGNMENT_DELAY
	      exponent_res_normalised_3$D_IN;
	if (exponent_res_overbiased_1$EN)
	  exponent_res_overbiased_1 <= `BSV_ASSIGNMENT_DELAY
	      exponent_res_overbiased_1$D_IN;
	if (exponent_res_overbiased_2$EN)
	  exponent_res_overbiased_2 <= `BSV_ASSIGNMENT_DELAY
	      exponent_res_overbiased_2$D_IN;
	if (got_A$EN) got_A <= `BSV_ASSIGNMENT_DELAY got_A$D_IN;
	if (got_B$EN) got_B <= `BSV_ASSIGNMENT_DELAY got_B$D_IN;
	if (got_final$EN) got_final <= `BSV_ASSIGNMENT_DELAY got_final$D_IN;
	if (input_1_64$EN)
	  input_1_64 <= `BSV_ASSIGNMENT_DELAY input_1_64$D_IN;
	if (input_2_64$EN)
	  input_2_64 <= `BSV_ASSIGNMENT_DELAY input_2_64$D_IN;
	if (mantissa_A$EN)
	  mantissa_A <= `BSV_ASSIGNMENT_DELAY mantissa_A$D_IN;
	if (mantissa_B$EN)
	  mantissa_B <= `BSV_ASSIGNMENT_DELAY mantissa_B$D_IN;
	if (mantissa_res_non_normalised$EN)
	  mantissa_res_non_normalised <= `BSV_ASSIGNMENT_DELAY
	      mantissa_res_non_normalised$D_IN;
	if (mantissa_res_non_normalised_reduced$EN)
	  mantissa_res_non_normalised_reduced <= `BSV_ASSIGNMENT_DELAY
	      mantissa_res_non_normalised_reduced$D_IN;
	if (mantissa_res_normalised$EN)
	  mantissa_res_normalised <= `BSV_ASSIGNMENT_DELAY
	      mantissa_res_normalised$D_IN;
	if (sign_out$EN) sign_out <= `BSV_ASSIGNMENT_DELAY sign_out$D_IN;
	if (stage1$EN) stage1 <= `BSV_ASSIGNMENT_DELAY stage1$D_IN;
	if (stage2$EN) stage2 <= `BSV_ASSIGNMENT_DELAY stage2$D_IN;
	if (stage3$EN) stage3 <= `BSV_ASSIGNMENT_DELAY stage3$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    answer = 64'hAAAAAAAAAAAAAAAA;
    exponent_res_normalised_1 = 12'hAAA;
    exponent_res_normalised_2 = 11'h2AA;
    exponent_res_normalised_3 = 11'h2AA;
    exponent_res_overbiased_1 = 12'hAAA;
    exponent_res_overbiased_2 = 12'hAAA;
    got_A = 1'h0;
    got_B = 1'h0;
    got_final = 1'h0;
    input_1_64 = 64'hAAAAAAAAAAAAAAAA;
    input_2_64 = 64'hAAAAAAAAAAAAAAAA;
    mantissa_A = 52'hAAAAAAAAAAAAA;
    mantissa_B = 52'hAAAAAAAAAAAAA;
    mantissa_res_non_normalised = 106'h2AAAAAAAAAAAAAAAAAAAAAAAAAA;
    mantissa_res_non_normalised_reduced = 52'hAAAAAAAAAAAAA;
    mantissa_res_normalised = 52'hAAAAAAAAAAAAA;
    sign_out = 1'h0;
    stage1 = 1'h0;
    stage2 = 1'h0;
    stage3 = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFPMul64

